// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package pgdb

import (
	"context"
)

const deleteSetting = `-- name: DeleteSetting :execrows
DELETE FROM settings
WHERE key = $1
`

func (q *Queries) DeleteSetting(ctx context.Context, key string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSetting, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSettingsNotIn = `-- name: DeleteSettingsNotIn :execrows
DELETE FROM settings
WHERE NOT (key = ANY($1::text[]))
`

func (q *Queries) DeleteSettingsNotIn(ctx context.Context, dollar_1 []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSettingsNotIn, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSetting = `-- name: GetSetting :one
SELECT key, value
FROM settings
WHERE key = $1
LIMIT 1
`

type GetSettingRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) GetSetting(ctx context.Context, key string) (*GetSettingRow, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var i GetSettingRow
	err := row.Scan(&i.Key, &i.Value)
	return &i, err
}

const insertSettingIfNotExists = `-- name: InsertSettingIfNotExists :exec
INSERT INTO settings (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO NOTHING
`

type InsertSettingIfNotExistsParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) InsertSettingIfNotExists(ctx context.Context, arg InsertSettingIfNotExistsParams) error {
	_, err := q.db.Exec(ctx, insertSettingIfNotExists, arg.Key, arg.Value)
	return err
}

const listSettings = `-- name: ListSettings :many
SELECT key, value
FROM settings
`

type ListSettingsRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) ListSettings(ctx context.Context) ([]*ListSettingsRow, error) {
	rows, err := q.db.Query(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListSettingsRow{}
	for rows.Next() {
		var i ListSettingsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSettingKey = `-- name: UpdateSettingKey :exec
UPDATE settings
SET key = $2
WHERE key = $1
`

type UpdateSettingKeyParams struct {
	Key   string `json:"key"`
	Key_2 string `json:"key_2"`
}

func (q *Queries) UpdateSettingKey(ctx context.Context, arg UpdateSettingKeyParams) error {
	_, err := q.db.Exec(ctx, updateSettingKey, arg.Key, arg.Key_2)
	return err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
`

type UpsertSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.Exec(ctx, upsertSetting, arg.Key, arg.Value)
	return err
}
